### ISSUE TITLE
Deleting old snapshots 

### ISSUE THREAD

**Issue by atais** [chase-miller/virtualbox-snapshot-create#3]
In file: `delete-old-snapshots.sh`

you have a command

```bash
VBoxManage snapshot "$vm" list | sed -e :a -e "$d;N;2,$1ba" -e 'P;D'  | awk -F "UUID: " '{print $2}' | awk -F ")" '{print $1}' | xargs -L1 VBoxManage snapshot "$vm" delete
```

which I assume should take all but last `$1` items.
Currently on `ubuntu 14.04` this line does not work for me, but it can be done much easier, instead of `sed`:

```bash
VBoxManage snapshot "$vm" list | head -n -"$1" | awk -F "UUID: " '{print $2}' | awk -F ")" '{print $1}' | xargs -L1 VBoxManage snapshot "$vm" delete
```

`head -n -K` gets all but last K items.

**Comment by camiller2** [comment]
Feel free to open a pull request with these changes :-)

**Comment by atais** [comment]
I would but I do not think anyone will merge it :disappointed:

**Comment by ezraholm50** [comment]
> I would but I do not think anyone will merge it :disappointed:

Just fork it and make the changes, I'm interested. Just post your fork in here if the development has stopped.

**Comment by atais** [comment]
ok I have created the PR. 

@ezraholm50 Read the PR comment if you are interested in the command's details.
